/**
 * Standardized error codes for Vortixy API.
 * Format: CATEGORY.SPECIFIC_ERROR
 */
export const ErrorCodes = {
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT.EXCEEDED",

  // Authentication & Security
  CSRF_INVALID: "AUTH.CSRF_INVALID",
  SAME_ORIGIN_REQUIRED: "AUTH.SAME_ORIGIN",
  FORBIDDEN_ORIGIN: "AUTH.FORBIDDEN_ORIGIN",
  UNAUTHORIZED: "AUTH.UNAUTHORIZED",

  // Validation
  INVALID_JSON: "VALIDATION.INVALID_JSON",
  INVALID_FIELDS: "VALIDATION.INVALID_FIELDS",
  PAYLOAD_TOO_LARGE: "VALIDATION.PAYLOAD_TOO_LARGE",
  INVALID_UUID: "VALIDATION.INVALID_UUID",

  // Checkout
  CHECKOUT_INVALID: "CHECKOUT.INVALID",
  CHECKOUT_SHIPPING_MISMATCH: "CHECKOUT.SHIPPING_MISMATCH",
  CHECKOUT_STOCK_INSUFFICIENT: "CHECKOUT.STOCK_INSUFFICIENT",
  CHECKOUT_CONCURRENT: "CHECKOUT.CONCURRENT",
  CHECKOUT_DUPLICATE: "CHECKOUT.DUPLICATE",
  TOO_MANY_ITEMS: "CHECKOUT.TOO_MANY_ITEMS",

  // Orders
  ORDER_NOT_FOUND: "ORDER.NOT_FOUND",
  ORDER_INVALID_TOKEN: "ORDER.INVALID_TOKEN",
  ORDER_CONFIRMATION_FAILED: "ORDER.CONFIRMATION_FAILED",

  // Internal
  SUPABASE_ERROR: "INTERNAL.SUPABASE_ERROR",
  SUPABASE_ADMIN_MISSING: "INTERNAL.SUPABASE_ADMIN_MISSING",
  INTERNAL_ERROR: "INTERNAL.ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
